export default quotes = ["Come! Learn the lessons in Yoga-practice.  Meditate.  Tear the veil.  Go.  Dwell in peace.",
"Samsara is essence-less. It is sapless like the stem of a plantain tree. It will vanish ultimately when you attain Samadhi.",
"Worldly life is Apurna (incomplete), finite, imperfect, limited. It is full of weaknesses, pains, sorrows, diseases.",
"Commence your journey on the divine path from today. All your anxiety and worry will end, then and there.",
"This world which consists of friends, enemies and neutrals, which affects you with pleasure and pain, is only a creation of your mind which is a product of ignorance.",
"The objects of the world act as intoxicants.",
"Do not be deceived by the charm of external objects. It is an illusion.",
"This world is a pit of live coals, a vale of tears. You cannot expect lasting bliss here.",
"A worldly man is very busy with the play toys of worldly objects. He forgets to look within and enjoy the eternal bliss of his Soul.",
"An ordinary worldly man lives in his emotions. He lives in his lower mind. He has no idea of intuition.",
"A worldly man has perverted mind. He is intoxicated with the wine of ego.",
"Vain are the ways of worldly men. Vanity is the foundation of society.",
"Be thou in this world as though you are a passerby on the road, or like a lotus in the water.",
"Verily, long is the way. Comrade! March fearlessly. Be patient. Success is sure. You will reach the goal assuredly.",
"This world is an inn. Start your homeward journey. Your original home is Param Dhama, the Immortal Abode of Brahman.",
"Seek the Immortal Atman hidden in the cave within your heart.",
"O nectar\’s son, O child of Immortality! Sing the song of strength. Sing the song of triumph. March forward fearlessly and reach the goal of illumination.",
"Tread the path of Truth. Meditate. Hear the voice of the Silence. Enter the Silence.",
"O Ram! Develop intense dispassion. Here is thy salvation.",
"Awaken thy heart! Happiness is here and now. Become a friend of humanity. Become a radiant Yogi. Strive. Endeavour.",
"Consider yourself a sojourner here, having come here with a definite mission, for attaining Self Realization.",
"Regain your lost divinity. There is no time to lose. Death marches close to your heels.",
"Will you for ever be sunk in the mire of Samsara? Come out of thy narrow ruts. Become a Yogi. Overcome the self by the Self.",
"Seek the immortal, all-blissful Soul within. You will enjoy everlasting happiness and peace.",
"Go beyond all that causes duality.",
"The cause of death is birth.",
"The cause of pain is pleasure.",
"End and beginning are dreams. Endless and beginning-less is the Soul, or Atman.",
"Philosophy deals with man, God, Brahman and Universe. Philosophy signifies love of wisdom.",
"If you exist, God also exists.",
"It is divinity that shapes, not only your ends, but also your acts, your words and thoughts.",
"Where is Peace? It is in the heart of a desireless man, who has controlled his senses and the mind.",
"You can elevate others only if you have elevated yourself. This world can be saved only by those who have already saved themselves. A prisoner cannot liberate other prisoners.",
"Roll up space like a piece of leather. Then alone, there will be an end to your sorrow and pain.",
"Delve deep into the ocean of the Upanishads and bring out the most precious Atmic pearl.",
"Know and then live the divine life, the Upanishadic life of Brahmic consciousness.",
"Brahman, the Absolute, is ever free. Know this. Know this and be ever free--free--free!",
"Come! Come! Practice Yoga. Meditate seriously. You will cross this ocean of darkness and ignorance and reach the Light and Life everlasting.",
"Learn the lessons of Yoga. Meditate. Tear the veil. Go. Dwell in peace.",
"Take the fullest advantage of this human birth. Have a real, inner, divine life. May divine grace illumine your spiritual path.  May the divine power actuate you to perform great deeds. May the divine grace transform you into divinity.",
"Desireless-ness, born of the love for the Eternal, is called Vairagya. There can be no religion without Vairagya.",
"Without dispassion, there can be no spirituality.",
"It is impossible to attain God Realization without renunciation.",
"Desireless-ness is the highest form of purity. Desireless-ness leads to immortality and eternal peace. Dispassion or desireless-ness is the drawing room of the Palace of God.",
"The essential condition of spirituality is the annihilation of the lower self and desire for sensual pleasures.",
"If you can get over the thirst for carnal pleasures in life, you have almost conquered all your enemies.",
"When you are free from attachment to all external objects the mind will be at peace.",
"You should renounce, the moment real Vairagya dawns in you.",
"Make Yoga the only purpose, aim, and real interest in your life. Plunge into Sadhana now and realize God.",
"Do not bother about spiritual experiences. Go ahead with your Sadhana. Knowledge dawns of its own accord.",
"Continue your Sadhana without any interruption. Sadhana is your best friend.",
"Sadhana should be as much a part of your daily life as eating, drinking and breathing.",
"Make a firm resolve. Be earnest. Be vigilant. Be advancing. March forward, O heroic soldier.",
"Develop fiery determination, iron will, burning dispassion and yearning for liberation. You will realize the Truth right now. Do or die.",
"Do not tell anybody except your Guru, the realizations and the visions and other experiences that you get during your Sadhana.",
"Awake, O aspirant! Do vigorous Sadhana. Burn all impurities. Attain illumination through meditation.",
"Of what avail is enjoyment, which is momentary? Seek the Bliss Eternal in your own Atman.",
"How hollow is a sensuous life of carnal enjoyment! Therefore, shun sensual pleasures.",
"Abandon the three K\’s - Kamini (lust), Kanchana (gold), and Kirti (fame). Then this World will not attract you.",
"Make discrimination and non attachment your sword to cut the tree of Samsara (the karmic cycle of birth and death).",
"There is no greater glory, there is no greater joy, than that of a life of renunciation and perfect Tyaga (renunciation of egoism and desires).  It is a grand life.  Renunciation alone can make you fearless and happy.",
"Hanker not after sensual pleasures. Know that the Infinite alone is Bliss. There is no pleasure in the sensual things of the world.",
"Do not allow the mind to wander about in sensual objects. Practice Nirodha, or self-restraint.",
"He who has no discrimination is childish. He runs after external pleasures and walks into the net of death.",
"Look within. Do not join with the senses any longer. Learn to discriminate. Become wise.",
"Through the intellect you know the difference between the permanent and the impermanent.",
"Cultivate discrimination between the Real and the unreal and you will realize the hollowness of the pleasures of sense-objects.",
"Learn to realize that sensual pleasure is never complete and full.",
"Teach yourself the miseries what over indulgence in sensual pleasures will bring to you.",
"Your strength should not be the strength of a gun and a bank balance. It should be the invincible strength born of wisdom and discrimination.",
"If you want God, you must turn your back to Worldly enjoyments. Give up sensual life, if you do not want death.",
"Think of the Immortal Soul or Atman. All thoughts of objects will perish by themselves.",
"Desire is poverty. Desire is the greatest impurity of the mind. Desire is the motive force for action. Desire in the mind is the real impurity. Even a spark of desire is a very great evil.",
"Desire rules in a passionate man whose heart is filled with Rajas. He gets bound. He becomes imperfect, and weak. He becomes limited. He is ignorant.",
"Your desire is never satiated, even though you possess the wealth of the whole world. Life is short. Time is fleeting. Desire is rampant. Slay desire, the enemy of peace.",
"Give up desire and craving. Seek the Grace of the Lord. Sing his Name, with dispassion and renunciation as your cymbals.",
"Eradicate all desire ruthlessly through inquiry, dispassion, aspiration and meditation.",
"Destruction of desire is Moksha, final emancipation.",
"Desire makes the mind impure.  Annihilate all desires. At once the mind becomes pure.",
"God alone can free you from desires and fears. Pray to Him for purity and courage.",
"Meditate on the desireless and fearless Brahman. You will become desireless and fearless.",
"Crave for a thing and you will get it. Renounce the craving, the object will follow you by itself.",
"Desire nothing. Give up all desires and be happy.",
"For a man of contentment, sovereignty of the whole world is no better than a bit of rotten straw. He is indeed miserable and poor, who is discontented.",
"Repeat Om. Chant Om. Sing Om. Meditate on Om. All desires will vanish. You will attain Self Realization.",
"Life is but a play. Play well, thy part in this drama.",
"If you are good, the whole world will be good for you.",
"The World exists, because the mind functions dualistically.",
"There is nothing good, nor evil. Thinking makes it so.",
"More than food, water and fire, man\’s need is sympathy, kindness and brotherhood.",
"The conquest of the lower nature, the overcoming of weakness, is the road to happiness.",
"Terrible is the fight put up by the senses.",
"Introspect.  Watch the mind. It will gradually grow calmer and calmer. You will be able to find your defects.",
"Divine life is full, infinite, perfect and blissful, therefore, lead the life divine.",
"Think correctly. Decide carefully. Work diligently.",
"The moment you turn your mind Godward, you will gain immense strength and peace.",
"Wish good to all beings. This will enrich your life and make you happy and peaceful.",
"Know thy Self and be free.",
"Religion gives solace to the weary pilgrim in this earth plane. It explains life\’s mystery to him. It shows the path to the immortal abode.",
"Religion is living in God. It is not mere discussion about God.",
"Religion consists of doing good to others, in the practice of love, mercy, truthfulness and purity in all walks of life.",
"Lead the divine life of Truth, Love and Purity.",
"Live to serve humanity.",
"Be good. Do good. Serve, Love, Give, Purify, Meditate, Realize. This is the religion of Siva. This is the religion of the members of the Divine Life Society.",
"Discipline the body, the senses and the mind.",
"Adopt the triple motto: Ahimsa, Satya, Brahmacharya (Non-Violence, Truthfulness, Celibacy).",
"Live in peace and harmony with your neighbours and fellow humanity.",
"Bear enmity to none. Do not vex others. Do not be vexed by others.",
"Forget and forgive. You will have peace. You will become divine.",
"If anyone proves to be faithless to you, be faithful to them always.",
"Forget the past. Begin life afresh. Face life boldly. A glorious future is awaiting you.",
"Youth is a state of the mind. It is not of time or period of life. Utilize well all opportunities. You can make your life sublime.",
"Persevere and be tenacious. You will reach success in everything.",
"Divine Life is a life of Love, Wisdom and Light.",
"Love all. Be one with all. See the One in all.",
"Love, Humility, Forgiveness, Patience, Compassion, Courage, Integrity, Nonviolence, Purity, Aspiration are qualities leading to Divinity.",
"Behold the Divinity in all beings. Greet everyone as the Lord himself. Feel the presence of the Lord everywhere.",
"Cling not to your ego, your lower self and limited mundane life. Soar high into the highest realms of eternal bliss.",
"Attachment is death. Non-attachment is life eternal. Renunciation is the bestower of peace and immortality.",
"Renounce pedantry, erudition and learning. Become childlike and silent. Now, you will realize the Self.",
"Spiritualize all your activities.",
"Let your eyes look with kindness, your tongue speak with sweetness, your hand touch with softness.",
"Let thy eyes not see anything but the image of the Lord. Let thy ears be filled with His praise. Let thy mind dwell on His Lotus feet.",
"Be thou compassionate as Buddha, pure as Bhishma, truthful as Harischandra, brave as Bhima.",
"Always do good to others. Be selfless. Mentally remove everything and be free. This is divine life. This is the direct way to Moksha/salvation.",
"Let your life be a radiance of Purity, Love, Sacrifice and Selfless Service.",
"Live in the Eternal. Be honest. Be sincere. Be truthful. Be alert. Be diligent. Be vigilant. Be bold. Be of good character.  Success and glory will be yours.",
"If you are truthful and pure in your daily life, you will inherit the kingdom of God.",
"Soak your life with remembrance of Lord. Dedicate your all to him. See him in everyone.",
"Do Japa. Sing Kirtan. Do charity. Practice meditation. Realize Atmic Bliss. May God bless you.",
"Be kind. Be compassionate. Be honest. Be sincere. Be truthful. Be bold. Be pure. Be wise. Be virtuous. Enquire: \"Who am I?\" Know the Self and be free. This is the summary of the teachings of Siva.",
"All are manifestations of the Lord. It is a shameful slur on you if you bear a grudge or ill will towards anybody.",
"Do not hate the evil hearted, the jealous and the selfish. It is they who promote your salvation.",
"Love and respect the Saints of every faith.",
"Avoid lip service, lip sympathy, and lip Vedanta - Three types of hypocrisy.",
"Theory is one thing and Life another. Become a practical man. Become a practical Vedantin.",
"The children are the builders of tomorrow. They are the future citizens. They are the destiny of the nation. Train them, discipline them, mold them properly.",
"Every child has within him a life force. Give him opportunities to express himself. Do not repress the life force. Education is introduction to Life. It must be non-sectarian. It must aim at friendship and fellowship with different communities.",
"Education must aim at helping the student to develop a strong healthy body and mind, self confidence, courage, ethical perfection, initiative and good character.",
"The training of intellect should go hand in hand with the unfoldment of the Soul.",
"Instruction in material and practical affairs should keep pace with instruction in Divine things.",
"Man\’s mental and moral growth has not kept pace with his technical and scientific advance.",
"Measure not education by material success. Education should not miss the true end of culture of moral and spiritual uplift.",
"Students think more of degrees and money than the true values of Life.",
"Education must make one fearless, \’I-less\’, \’mine-less\’ and desire-less.",
"The education of the present day students is a bit too bookish. The students aim at getting degrees more than the real education of useful practical knowledge. The students go through their college career rather aimlessly, without a definite plan or purpose.",
"Real education aims at controlling the mind, annihilating egoism, cultivating divine virtues and attaining knowledge of the Self/Brahma-Jnana.",
"Education must be put to proper use, to unfold one\’s consciousness, to help community and country achieve prosperity.",
"Science is not the enemy of religion, but a preparation for it.",
"Go beyond science, into the region of metaphysics. Real religion is beyond argument. It can only be experienced both inwardly and outwardly.",
"Satsanga is the first pillar in the temple of Self Realization. Therefore seek the company of sages.",
"A sage is a fountain of spiritual wisdom. Approach him with all humility and reverence. He will impart to you divine wisdom.",
"A saint has learned to renounce the objects of the world, all ambition and all reputation.",
"Only a sincere and earnest Sadhaka/spiritual aspirant knows the value of Satsang, association with Saints and Sages. Satsang gives the aspirant inner spiritual strength to face the struggle, overcome temptations, kill inner cravings and fill the mind with positive divine thoughts.",
"A very good Sadhaka can not only inspire people, but also lead them and guide them along the spiritual path.",
"Remember the great saints and sages. You will be inspired. They are not dead. They are more alive today than ever before.",
"A real, dynamic Sannyasin/renunciant molds the nation\’s civilization and shapes its destiny.",
"Humility, Courage, Compassion, Peace, Wisdom, Forgiveness, Self restraint, Equal vision and Balanced mind adorn the Sages, like many ornaments.",
"Association with Saints and Sages is difficult to get. They are inaccessible. Such association is unfailing in its results.",
"A Saint or Sage is a spiritual washerman. He applies the soap of Illumination, beats his clothes on the rock of Serenity and washes them in the river of Wisdom.",
"A Saint\’s life is one long prayer.",
"There are pitfalls in every step in Yoga. Therefore have a Guru or guide to lead you on.",
"To receive initiation of Bhagvannama from a Guru is a great blessing. Mantra Chaitanya, the power hidden in the Mantra, is easily awakened.",
"The Guru will appear to you only through the Lord\’s Grace. Guru is God. So adore your Guru. You will yourself have to lead a pure life. Your preceptor cannot do this for you.",
"Satsanga (association with Sages); Discrimination between the Real and the Unreal; Dispassion; Inquiry of \"Who am I?\" and Meditation will bestow eternal bliss and immortality on you.",
"A weak, emaciated and decrepit old body is not fit for Yoga Sadhana. Let your body be strong, healthy and pure. Body building is nation building.",
"Be not a victim to imaginary ills and diseases.",
"Practice Sirshasana, Sarvangasana, Matsyasana and Paschimottanasana and a few rounds of Sukha Purvaka Pranayama in the early morning. You will possess wonderful health.",
"Thinking of disease constantly will intensify it. Feel always \"I am healthy in body and mind\".",
"Take pure food. You will have pure intellect and good memory. You will attain Self Realization with the aid of the pure intellect and good memory.",
"Offer first whatever you eat to the Lord. Take it as His Prasad. This will purify your food.",
"Every disease is a Karmic purgation. Take illness as the Lord\’s blessing. All diseases take their origin in the mind. Treat the mind first. Physical diseases will disappear by themselves.",
"Again and again assert: \"I am the bodiless, diseaseless, all pervading, Immortal Soul/Atman\".",
"Worry has caused new deadlier diseases like high blood pressure, heart trouble and nervous breakdown. Fear alone checks the flow of blood and even poisons the blood. Laughter and cheerfulness increases the circulation of blood. They are blood tonics.",
"Ill health is a myth. It does not exist beyond the range of the physical and mental sheaths. The body and the mind alone are subject to diseases. The Atman, your true Self, is beyond these and therefore eternally free from diseases and death.",
"Brahmacharya rejuvenates. It augments energy, nerve and brain power and vitality. It is the life ray of man.",
"The practice of Hatha Yoga is necessary to keep you quite fit, hale and hearty.",
"Hatha Yoga is a course of psycho-physiological discipline for the attainment of complete mastery over the body, the nervous system and Prana.",
"Control of the body and the subordination of the body to the Spirit, makes the Hatha Yoga system an invaluable aid to the aspirant.",
"Diseases, worries, troubles can only affect the physical and the mental, but not the Spiritual Self/Atman.",
"Disharmony of thought, word and deed is the cause for all troubles, miseries and quarrels in this World.",
"During illness detach yourself from the body. Connect the mind with the Buddhi and Soul. \"As you think, so do you become.\" Therefore, assert you are healthy. Disease will take to its heels.",
"Enrich your blood through Japa, Kirtan, Meditation, Sattva, Pranayama, Asanas, tomatoes, grapes, spinach, pure air and sunlight.",
"Abstemious eating is the most important means of attaining longevity.",
"Yoni Mudra helps in the closure of the Nine Doors/Navadvara and in the hearing of the Anahata sounds.",
"Drive this body car intelligently. Relax perfectly. Breathe rhythmically. Meditate regularly. You will enjoy happiness, health and long Life.",
"The greatest obstacles to Self Realization are desire for property, desire for wealth and desire for name and fame. Desire is born of ignorance. The fundamental desire is the urge for a mate. Destruction of desire is destruction of ignorance.",
"Desire is the seed from which sprouts ceaseless births. Desire arises from a sense of imperfection or limitation, by identifying with the finite body, mind and ego.",
"As is your desire, so is your will. As is your will, so is your action. He who is desireless will have an absolute free will.",
"He is ever blissful who longs for nothing and fears nothing.",
"If you crave for objects, then they come in the way of your God Realization.",
"The tendency to think of sense objects is indeed the cause of bondage or transmigration.",
"Lust and greed are hindrances to renunciation. Kamini (lust), Kanchana (gold), Kirti (fame) are the three obstacles to God realization. A lustful and greedy man is not fit for spiritual life.",
"Anger, lust and greed are the basic enemies of spirituality.",
"A weak will is overpowered by the strong desire. Reduce your desires and live self contented.",
"Wherever there is Raga (dislike) there is fear.",
"Root out desire by Viveka (discrimination) and Vairagya (dispassion).",
"The mind is the slayer of Peace. The mind is the slayer of Truth. Make your mind your friend.",
"Control your mind and the senses. This is the greatest victory.",
"The mind is responsible for the feelings of pleasure and pain. Controlling of the mind is the highest Yoga.",
"If the mind is controlled it is then capable of great service. If it is not subdued it creates endless pain and suffering.",
"He alone who has controlled his mind will be ever peaceful and joyful.",
"Use your mind as a filter. Watch and do not allow any useless thought to enter the mind. Filter all useless thoughts.",
"The greatest weakness is doubt. Doubt is thy enemy. Doubt is the greatest sin. Slay this doubt. Slay the slayer mind.",
"The intellect is a hindrance. Too much of arguing is the bane of modern civilization.",
"Belief determines conduct. Thought determines character. A man of perverted mind, or a doubting person, will not receive spiritual knowledge.",
"Man is changed by every thought he thinks and by every action he does.",
"All that you are is the result of what you have thought. Life is founded by your thoughts. It is made up of your thoughts.",
"The root evil, brought about your bondage, is Moha/infatuated love. Moha is delusion. It is not pure love. It is attachment to flesh, but not to the Soul.",
"Control the lower emotions. Emotions are waste of energy and power, clouding the light of reason and wearing on the physical body.",
"The spectator derives more joy than the actor, so be a witness of your thoughts. You will enjoy more lasting happiness.",
"Annihilate double dealing, diplomacy, jealousy, self conceit and hypocrisy. These are the enemies of Devotion, Peace and Wisdom.",
"Hatred, pride, harshness, revengefulness, anger, cruelty, greed are brutal qualities. Seek Wisdom, not powers. Powers are obstacles to God Realization.",
"O mind! Go back to the original sweet home of Brahman, wherein alone lies everlasting Peace and Eternal Bliss.",
"In whatever situation God places you, it is only for your betterment. Kindly do not be discouraged.",
"God does everything for your own good. Later on you will know this. Be patient.",
"God alone can protect you from the mundane troubles, difficulties, tribulations and miseries. God listens to and answers all your prayers. Let the prayer come from the bottom of your heart.",
"The more you yearn to turn a new leaf in your Life and lead a pure, divine Life, the more opportunities come your way.",
"The first lesson in the scripture of man\’s life is Prayer. Let Prayer be the basis of your life.",
"Adversity is a Key that opens the gate to Eternal Bliss.",
"Be strong. Be courageous. Fear nothing. Nothing can obstruct thee. Find thy rest in the Supreme Soul. March fearlessly in the path of spirituality.",
"Nothing is lost when the candle burns. No spiritual effort goes in vain.",
"The initial stages in Sadhana will be one of ups and downs. Obstacles and unfavourable circumstances are God sent chances to make you more steady and strong in will.",
"The harder the struggle the more glorious the triumph. Self Realization demands a very great struggle.",
"You say your life has been one of suffering. Think of Prahlada. Think of Dhruva. Draw inspiration from them. Be calm and unperturbed.",
"Face the worst, bravely. Fight for the best, boldly.",
"Time is the soul of the World. It is the richest treasure. Waste not even a second.",
"Time is more precious than money.",
"Little acts make great actions.",
"Spiritual awakening is a gradual progress of the unfolding of the Consciousness of the Divine.",
"Work out your salvation in and through this World.",
"Always strive to lead an inner spiritual Life in your own Atman/Self.",
"This marvellous World is a great University of Wisdom. Learn your lessons and become wise.",
"Life travels through many conflicts and trials. Life is a series of conquests. Fight bravely with the internal foes on the battleground of your heart.",
"Dwell in the Divine. Live and move in it. Get absorbed in the Divine Flame.",
"Strive, strive, strive. This is the sacred Mantra to success in everything.",
"Be active, but not noisy.",
"Keep a fixed time each day for study of scriptures (Svadhaya). Study thoroughly, prayerfully and unhurriedly, with an alert mind and without interruption.",
"The Gita is the source of Power and Wisdom. It teaches you to embrace Dharma (righteousness) and abandon Adharma (nonrighteousness). It imparts lessons on ethics, philosophy, devotion and Yoga.",
"Make Yoga a spiritual reality in your daily Life. Become a practical Yogi.",
"Laziness is the father of disappointment and failure.",
"A craving for comforts can weaken your fibre. Lead a simple and hard life. Be strong. Be sinewy.",
"Today many have turned away from the Rishis\’ ideals of Service, Love, Sacrifice, Renunciation, Dispassion, Devotion and Meditation, hence lives are suffering. There is unrest, war, exploitation and misery.",
"In the message of the Rishis and Sages is the hope of India, the hope of the whole World, and the hope of a new civilization.",
"Let your Life become a continuous Yajna/sacrifice to God.",
"Obey the law and you are blessed. Disobey the law and you are punished.",
"Time is Life. Utilize time profitably in spiritual pursuits.",
"Today is your own. Tomorrow perchance may never come.",
"You have wasted much of your life. A little time is left. Make the best use of it. You too, can realize God and be ever happy.",
"Spend your Life of retirement usefully in Japa, Kirtan, Meditation and Selfless Service.",
"Do not waste even half a second. Plunge yourself into Japa, Kirtan and Service of saints and the poor. Meditate.",
"Depend upon the Lord. Care not for tomorrow.",
"Learn lessons from the birds and animals.",
"Sing the song divine. Let thy face gleam with light.",
"Whatever happens, receive it with a smiling face. Be ever delighted in your own all blissful Atman/Soul.",
"Learn to depend entirely on God. Wait and watch. Despair not. Worry not. He will shower His choicest blessings on thee.",
"The Lord\’s ways are mysterious. There is something good even in all seeming failures. You are not able to see that now. Time will reveal it. Be patient.",
"Never become impatient in the spiritual path. Be patient. Be calm. Strive, Strive, Strive.",
"Give up this inordinate clinging to this body. Let the body go. Identify yourself with the all pervading immortal Soul.",
"Thou art the child of Immortality. Thou art the Nectar\’s son. Sing a song of strength. Be bold. Be brave. Be as strong as adamant.",
"Do not worry about obstacles. They will pass away.",
"Take refuge in the Lord and His name.",
"God is watching all your thoughts and movements. He will remove all obstacles.",
"Dispassion and faith are prerequisites for spiritual Sadhana.",
"Without renunciation no spiritual progress is ever possible. Renunciation is wisdom.",
"Cowards are not fit to take to the life of renunciation.",
"Renunciation is very difficult. Very few renounce. Internal renunciation is absolutely necessary. External renunciation is also beneficial and necessary.",
"An aspirant must have purity of mind, a real thirst for knowledge and perseverance.",
"Sincerity is lacking in most aspirants. That is the root of slackness.",
"Temperaments are different in individuals, but all individuals have to aim for the attainment of a common goal - the achievement of a common purpose - the one common consciousness of Brahman.",
"Be calm. Be cheerful. Be courageous. Be self-controlled.",
"Always maintain serenity under all conditions and circumstances.",
"Absolute desirelessness is the most important of all qualifications required of the disciple.",
"Remember and practice the \"Six S\’s\" - Santi (Peace), Santosha (Contentment), Satsanga (association with Sages), Satya (Truthfulness), Serenity and Seclusion.",
"Remember and Practice the \"Three D\’s\" — Discrimination (Viveka), Dispassion (Vairagya) and Determination.",
"To the earnest aspirant, the lives of Saints always stand as milestones guiding his way.",
"Annihilate desires. Subdue the mind. Subjugate the senses. Overcome the six enemies, the Shad Ripus. This is the holy warfare of spiritual aspirants.",
"No one who is thirsting for name, fame, power and lordship and enjoyment can achieve success in Yoga.",
"If you are drawn to the psychic powers/Siddhis you will miss the supreme goal. Beware of Siddhis!",
"The real spiritual progress of the aspirant is measured by the extent to which he achieves inner tranquillity.",
"Tapasya (austerities) does not mean that you cover you body with ashes and dust. Serve. Love. Give. Purify. Meditate. Realize. Be Good. Do Good. That is Tapasya.",
"Have faith, faith, faith. Know thy Self. Realize thy essential nature.",
"Hear what is auspicious. See what is auspicious. Do what is auspicious. You will soon attain Self Realization.",
"With increase of your yearning to realize, God will increase the clamour of the evil forces to take more complete possession of you. Therefore, be regular and vigourous in your Sadhana.",
"Persevere. Slowly increase the time spent in religious practices, by reducing wastage in idle talks and other useless pursuits.",
"Do your duties well. Study the scriptures under your Guru. Aspire intensely for Self Realization. Serve your Guru wholeheartedly. Then alone will you attain Self Realization.",
"Create your inner world. Carry with you your own inner companions of Shanti (Peace), Santosha (Contentment), Inquiry and Courage.",
"Strive with faith and single minded devotion. You will come out victorious in the end.",
"Loosen all ties first. Cross the barrier of illusion. Go beyond the emptiness, the void. Be brave. Look not back. March forward. Finally reach the realm of Eternal Sunshine.",
"Cling not to the intellect. Inquire. Transcend the intellect. Enter the realm of Illumination and Enlightenment.",
"Mentally detach yourself from everything. Intensify your Vairagya/Dispassion.",
"Know the value of time. You cannot salvage a second spent in worthless ways. Time is most precious.",
"Utilize every second in spiritual pursuits and service.",
"Do not love leisure. Waste not a minute. Be bold. Realize the Truth, here and now!",
"Associate always with the inner pure Consciousness. Get yourself established in the pure, absolute consciousness.",
"The senses and the mind are your real enemies. Conquer them.",
"To make the mind obey is a spiritual discipline.",
"Be humble and grateful.",
"Introspect. Analyze your own mind and try to improve it. Introspect and find your eternal Self.",
"Lead an inner spiritual life. Fight against the dark evil forces.",
"Take spiritual resolves and stick to them. This will help you to evolve and to reach the goal quickly. Stick to your resolve tenaciously. This will strengthen your willpower.",
"Conquer alasya (laziness) by asanas (yoga postures), Pranayama (controlled breathing) and light Sattvic (pure) food.",
"Anger, lust, greed, jealousy, hatred will always lurk in your subconscious mind. Beware. Be cautious. Be vigilant. Be alert. Eradicate them. Otherwise, they will gain strength and will crush you later on and swallow all your Sadhana.",
"Curb your passion slowly by Japa, Prayer, Meditation, Satsanga, Study of scriptures and Sattvic food.",
"Sharpen the intellect. Thin out the ego. Purify the mind.  ",
"Do the work of self purification rigorously. Grow in spiritual strength day by day.",
"Purity of mind, annihilation of ego, dispassion or disgust for worldly objects and keen aspiration are preliminary essentials for God Realization.",
"Give up your life, if you want to live.",
"The old evil forces will try to regain an entrance into the mind. Keep a vigilant watch.",
"The preceptor will only point the way. Search deeply and steadfastly for the Atman that dwells in your heart through introspection, self-analysis and meditation.",
"O aspirant! Do not keep money. Money will slacken your dispassion, weaken your will and hinder your spiritual progress.",
"Even a little victory in the inner battle with your mind and senses will develop your willpower and give more assurance and courage. But do not be swayed by success. Be humble and grateful.",
"Learn lessons of equal vision from the sun, the fire, the river, the flowers and the air. They serve the peasant and the king, the saint and the sinner, the clerk and the minister.",
"Lead a life of austerity and seclusion. In knowledge and austerity lies the secret of spiritual courage.",
"Promise not what you cannot fulfill. If you promise, carry it out at any cost.",
"Calm thy mind. Know thy essential divine nature. Do not run after sensual pleasures. Seek the immortal Atmic Bliss.",
"Perfect yourself first. Save yourself first. Have purity of motive. Reform thyself first.",
"You can give up wife and children, you can abandon wealth, but it is difficult to relinquish fame.",
"Rely upon nothing other than God.",
"Follow the right, unswerving at any cost. Care not of public opinion or criticism.",
"Keep a small Gita book, a small rosary of mala beads and a small mantra notebook in your pocket. Utilize these during your leisure.",
"Speak no evil. Hear no evil. See no evil. Think no evil. Do no evil. You will soon attain God Realization.",
"God walks in the garb of a beggar. He moans in pain in the guise of the sick. Open your eyes. See Him in all. Serve all. Love all.",
"Purify. Meditate. Unfold the divinity. This is your foremost duty.",
"Adapt yourself to your surroundings and environments. You will enjoy peace and strength.",
"Cultivate strong patience, under all crushing trials and intense forbearance, in the face of malignant persecution. You will succeed in every attempt.",
"Be humble, unassuming and charitable towards all.",
"There is no greater obstacle to divine life than the craving for carnal pleasures.",
"Constant and eternal vigilance is required in the spiritual struggle.",
"If you control the tongue, you have controlled all the senses.",
"Strengthen your will. Be bold. Be prepared. The hour of trial and test will come.",
"Annihilate lust through inquiry, dispassion and meditation.",
"Be childlike. Be simple. Be humble. The portals of the Temple of Wisdom are open unto the humble and simple.",
"Sit silent. Calm thy mind. Make it pure. Have one pointed devotion. You will enjoy eternal peace and bliss.",
"Meditation is the key by which the doors of the immortal citadel are opened.",
"Meditation leads to Samadhi, the superconscious state.",
"Meditation links you with Brahman, the Absolute.",
"Regular meditation alone can give you true happiness.",
"Meditation is a positive vital dynamic process. It transforms man into Divinity.",
"Meditate on the Self/Atman that dwells in your own heart. Dive deep in to the ocean of bliss.",
"Meditation is death for the mind, the demonic king of the passions and senses.",
"Religion, philosophy and meditation must go hand in hand.",
"Meditate and feel the living presence within and around you.",
"Make haste. Do not waver. Plunge into meditation. Reach the goal now.",
"Open thy heart. Open the consciousness to the Lord in daily meditation. Feel yourself nearer to His Divine Effulgence.",
"When you do Japa, when you meditate, the mind is freed from its distractive nature.",
"Know that within thy very heart abides the Cosmic Indwelling Presence of God. There is no holier shrine than a purified heart. Withdraw the senses. Enter this temple and commune with Him during silent, profound meditation.",
"Deep beneath the noise and storm on the surface, deep beneath the surging mental waves, there is that stupendous ocean of peace and stillness. Realize this through deep and intense meditation.",
"Practice meditation regularly. Dive deeper and deeper in the recesses of your heart.",
"Meditate on the right significance of Tat Tvam Asi (\"Thou art That\", \"I am He\") Mahavakya (Great Proclamation). You will attain Self Realization.",
"Meditate. Go down into the chambers or your heart. Go down deep, deep. Realize Divinity.",
"He who practices renunciation and meditation, serves the World more than the social and political leaders, platform lectures or founders of institutions.",
"The spiritual consciousness dawns during silent meditation. You forget the world and the body during meditation.",
"During meditation you are in the presence of the Supreme Being.",
"Where is God? Look within, my child! Behold! He abides within thy heart. Feel His Presence.",
"Meditation will bring light in your heart. Therefore meditate, meditate. ",
"Meditation raises you to the highest realm of divine knowledge, eternal joy and sunshine, therefore meditate, meditate.",
"Meditation is the divine ladder that helps the aspirant rise to the abode of immortal bliss of Brahman, therefore meditate, meditate. ",
"Meditation is the divine ladder that connects earth and the immortal citadel. Meditate. Meditate.",
"I have one world for all aspirants. \"Meditate\".",
"Meditation is painful in the beginning, but it bestows Immortal Bliss and supreme joy in the end.",
"Make the Rajoguna (Excitement/Activity) less and less prominent. Allow the Sattvaguna (Purity) to become preponderant. Then alone will the mind become calm and the meditation steady and peaceful.",
"Be regular in your meditation. If you miss a single day\’s practice, a week\’s effort may be necessary to make up for the loss.",
"Sit and meditate. Watch the mind. If the mind wanders, think you are the witness.",
"When the mind wanders, repeat some Stotras (Spiritual Verses), hymns, verses from the Gita or the Upanishads.",
"If you get a headache, stop your meditation for a few days, but do Nama Smarana (remember the name of God) always. Reduce the period of meditation.",
"When you meditate, some irrelevant thoughts may enter the mind. Do not repress them. Let them pass along.",
"When you sit for meditation give up domestic cares, business anxieties, thoughts of office, hope and ambitions. Make the room dark. Close the windows and doors and draw the curtain.",
"You need not wait for ethical perfection, before you start meditation.",
"Practice Ahimsa (Non Violence), Satyam (Truth), and Brahmacharya (Celibacy). At the same time practice meditation, also.",
"Meditation helps self purification.",
"Meditation purifies and strengthens your heart. It steadies your nerves. It augments the brain power. It shows you the next step in the spiritual path.",
"Laziness is a great obstacle in meditation. He who meditates daily will be free from pain, sorrow, weakness and troubles.",
"Through regular meditation the mind gradually becomes more and more calm. All preoccupations vanish.",
"Meditation bestows a spiritual poise. It helps the aspirant to face life with strength, joy and liveliness.",
"Regular meditation makes the mind less powerful in extroverted tendencies.",
"The one pointed mind (Ekagrata) is absolutely necessary for concentration, meditation and Samadhi.",
"When you meditate on \’OM\’ the mind gets purified.",
"The lamp of faith must be steadily fed by contact with sages and vigilantly trimmed by meditation.",
"As soon as you get up from your bed in the early morning, do Japa and Meditation, then practice Asana and Pranayama.",
"Pray. Meditate and march further and forward every day towards you goal.",
"Sit for meditation. Close your eyes. Close your mind to every impression from the five senses.",
"Do not force the mind to meditate. Understand the ways of the mind first. Cultivate virtues. Study the nature of the three Gunas (Primary Natural Forces). Purify. Only then meditation will be smooth and easy.",
"If the entire form of your Ishta-devata/deity does not appear in meditation, try to visualize and part of the form, the face or the feet.",
"Bhava (the mental attitude) is more important than the object on which you meditate.",
"Meditation is the very essence and life of all spiritual Sadhanas.",
"Be regular in your meditation. You will reap a rich spiritual harvest.",
"Practice meditation until perfection is attained, until the goal is reached.",
"Meditate. Realize. Proclaim to the World: \"I am the imperishable Atman. I am the invulnerable Atman. I am Atma Samrat (Self King). I am King of Kings.\"",
"Sahaja Samadhi (God Consciousness in the Waking World) is your centre, Life, Soul and goal.",
"Intuition is the integral experience in whole.",
"In Samadhi, communion with the Lord, all clamouring of desire is silenced. All sound is stilled. There is perfect peace.",
"Samadhi is a spiritual rebirth. It is Life Eternal. First there is a flash of intuition. Then comes perfect illumination.",
"In Nirvikalpa Samadhi, the mind is burnt out in total.",
"To remain absorbed in Brahman, conscious of one\’s identity with the Supreme Self, is named Turiya/Nivikalpa Samadhi.",
"Spiritual experience is indivisible experience. It is Experience Whole.",
"Samadhi is the most excellent form of Tapas (austerity). This is incessant Tapas. This is glorious, sublime, lofty Tapas. It is the Tapas of Tapas.",
"Memory (Smrti) is a mental activity. It brings about pleasure and pain. It must be suppressed before you enter into Samadhi.",
"Samadhi is awareness of the One\’s Essence.",
"In Samadhi, there is no sequence in spiritual experience. All things are directly comprehended, not one after another, but all at once (Yogavat).",
"There ha	s been exceptional instances when illumination has come suddenly and has instantly transformed Life.",
"Any scientific attempt to probe the Infinite will prove futile. The only scientific method is intuitional.",
"Develop the eye of Intuition. Have a vision of the Infinite.",
"Assert and affirm \"I am the immortal Being\". Realize the Self, now and here!",
"Identify yourself with the all pervading Self. Lead the Life of Oneness and Unity.",
"You cannot realize the Absolute (the Infinite) until you have overcome the body idea.",
"You have to go beyond your limitations and recognize yourself as the Absolute Being through purity, devotion, aspiration and meditation.",
"Transcend the mind (Manas) and the intellect (Buddhi).",
"\"I enjoy in all bodies. I suffer in all bodies. I see through all eyes. I hear through all ears. I work through all hands.\" This is the feeling of a Sage, a Vedantin.",
"A Sage is unmoved and non agitated in all conditions and environments and all circumstances, because he abides in his own Satchidananda (Existence-Knowledge-Bliss) Svarupa (Nature of the Self).",
"The light is within thee. Let the light shine.",
"Rest peacefully in the transcendent Silence.",
"Do vigorous Yoga Sadhana. Be sincere. Be patient. Victory shall always be yours.",
"Plod on. Strive, strive. Meditate, meditate. March on, brave lion, O Adhyatmic (spiritual) hero.",
"Persevere. Plod on in your Sadhana. Give up idle talk, tall talk, gossiping and back biting. Save your time.",
"Faith and practice can enable you to overcome every obstacle in the spiritual path.",
"Stand up, O hero! O seeker after Truth! Life is a battle-field. Fight bravely. Come out victoriously.",
"Conquer the hurdles. Give a bold front and continue the spiritual practice vigorously, in right earnest.",
"Never worry about what other people say or think. Do the right thing. Have a clear conscience and roam about happily.",
"Be regular in your Japa, Kirtan and Meditation. You will feel refreshed, renewed, rejuvenated, uplifted and inspired.",
"A thirsting aspirant should Practice self-denial.",
"Tear aside all limitations. Break all fetters. Go beyond all bounds.",
"Develop the head, the heart and the hand harmoniously.",
"Get up now. This is Brahmamuhurta (Auspicious Early Morning Time). Everywhere is silence. Nature herself is at peace. Now you can retire peacefully into the inner chambers of your heart.",
"Continually remember the Lord, who has given you existence and intelligence. Lead the life of self-restraint and self-denial. You will soon attain Unity with God.",
"Purify. Control the senses and the mind. Meditate and reach the abode of Bliss Immortal.",
"There should be a great demand for God from within. You should be spiritually hungry. Then alone will the Lord fill you with His grace.",
"The more intensely you desire for reaching the Goal, the more rapidly you advance towards it.",
"When selfishness is destroyed, there is an uninterrupted flow of spiritual force and Grace from Lord into your pure heart.",
"Become a child. Then alone the Divine Light and Grace will descend.",
"Divine Light and Grace will descend only upon the Sattvic (pure) mind, because only a pure mind can receive it.",
"Be pure, guileless, innocent and egoless like a child.",
"Be simple, innocent, childlike, righteous, generous and charitable. This will make you Divine.",
"Keep your heart tranquil, pure, empty of desires and thoughts. Then alone the Divine Light and Grace will descend.",
"The more you polish the surface of your inner heart, through practice of Dispassion and Meditation, the more the Lord\’s Grace and effulgence will shine there.",
"Only Divine Grace can eradicate lust, anger and delusion. A few drops of the Lord\’s Grace are the highest acquisition.",
"The means of getting God\’s Grace is not by learning, but by Bhakti. ",
"Divine Grace is in proportion to the degree of self-surrender.",
"God is an all-pervading, all-permeating, inter-penetrating essence. He is the Source for the World, Vedas and everything. He is embodiment of Love, Wisdom and Bliss.",
"All mortal things are shadows. God is the only Real Immortal Substance. He is in all. All things are in Him. He is all-in-all. All things are in Him. Inside and outside, He pervades and penetrates everything that exists.",
"Peace, God, Atman, Brahman, Immortal, Emancipation are synonymous terms.",
"Brahman is a living, dynamic spirit - the source and container for everything.",
"Brahman is not only the efficient or operative cause of the World, but its material cause, as well.",
"The Supreme is indefinable. Scholars give intellectual accounts of it, which are not absolutely true.",
"Brahman is not a metaphysical abstraction. It is the fullest and the most real Being.",
"Brahman has no expression, no sensation, no appetite, no will (in the sense of desire) and no feelings (in the sense of passions).",
"God\’s thinking is intuitive. He sees all things at once. He sees them whole.",
"The Director of the Mind, Intellect and Senses is no other than the all merciful Lord, your inner ruler, Antaryamin. Know Him and be free.",
"God is all full. He is self contained. He is eternal satisfaction.",
"God pervades the entire Universe. He is the Soul of this World (Visva Atman).",
"God is the indweller of you heart. He watches all your thoughts. Therefore, you cannot deceive Him.",
"God is the breath in your nose and the light in your eyes. God is the root of all Joy, Strength, Peace and Bliss.",
"Power, beauty, fame, prosperity, strength, fortitude are manifestations of the Lord.",
"God is not a dictator. He is not an autocratic ruler of this World. He is your loving father, kind mother and Immortal friend.",
"God is Love. Love is God. God is sweeter than the sweetest thing. He is all-milk, all-love, all-sweetness. He is the inflowing honey and nectar.",
"God is the root of all Joy, Strength, Peace and Bliss. ",
"Sweeter than sugar candy, brighter than the Sun, is God (Brahman). ",
"Sweet is mango. Sweet is music. Sweet is a good man. But, the Lord is far more sweeter than you can ever imagine.",
"The Inner Voice speaks unto him who has annihilated his ego (false personality).",
"God is Truth. Truth is God. Truth is infinity. Infinity is Eternity. Infinity is immortality.",
"Truth is God or Brahman. That which exists in the past, present and future, that which is unchanging and imperishable is Truth.",
"Truth alone is one without a second.",
"Truth is infinite. Truth is Absolute. Truth is immortality. Truth is eternal.",
"Truth is Brahman. Truth is as true today as it was millions of years ago and will be millions of years hence. That is the test of Truth.",
"Truth is immense. Truth is eternal. Truth can only be experienced by regular and ceaseless meditation. Realize this Truth and be free.",
"Truth is eternal Life and Existence. Truth is silence. Truth is immortal Essence.",
"Words may change, modes of approach may change, but Truth shines as the Absolute Reality.",
"Truth beckons to man to strive by all means in his power to experience it, to merge in it and then to know that Truth alone is, one without a second.",
"Truth is to be perceived intuitively or realized.",
"The Substance of Truth or Divinity is made up of bliss, peace, purity, courage, consciousness or wisdom. Know yourself, O Ram, to be of this divine substance or essence.",
"Infinite is divisionless Existence. Existence is Truth Absolute/Brahman.",
"The ultimate Reality cannot be made into an objective representation which the finite intellect can grasp.",
"Truth\’s abode is in Truth. Satyam (Truth) Anantam (Unlimited).",
"Truth is simple. Truth always expresses itself with the greatest simplicity.",
"Truth is Brahman. Truth reveals itself only to those who seek and love it.",
"The Absolute is beyond thought. No thinking can conceive of him.",
"Brahman/the Absolute is the basic reality in all illusory phenomena. It supports all.",
"Absolute is neither a subject nor an object of knowledge. It is Pure Consciousness.",
"Pure Consciousness is always one and is ever secondless. It is eternal.  We cannot conceive of two consciousnesses.",
"Brahman/the Absolute is not conscious. It is consciousness itself. Brahman does not exist. It is existence itself. Brahman is not blissful. It is bliss itself.",
"Pure or Absolute Consciousness is Brahman (The Absolute). Pure Consciousness is the same as Pure Bliss.",
"Brahman(The Absolute) is of an absolutely homogeneous nature. It is pure Being. It is indivisible consciousness.",
"Consciousness is not an attribute of Brahman. It constitutes its very essence or substance.",
"Brahman is not a thinking being, but pure consciousness itself.",
"Pure Consciousness is Brahman. It is not the individual\’s ego consciousness. It is Absolute Consciousness.",
"Brahman is the Absolute. Absoluteness is not in the need of either knowing anything or doing anything because of it\’s secondless.",
"The Nature of the Absolute is Peace. Absolute Peace, Perfect Peace, Unutterable Peace.",
"Brahman is the realm of intuition or Pure Wisdom. There is no thought here. The Knower and the Knowledge blend into one.",
"Wisdom is not the attribute of Brahman or the Absolute.  It is very stuff or essence of Truth.  It is the essence of Existence.",
"There are no desires in Brahman or the Infinite.  Brahman is ever pure (Nitya Suddha)",
"An atheist denies God.  The denier exists.  Existence is God or Brahman.",
"Brahman or the Absolute is an essence.  There are no parts or divisions in the Essence.  This Essence is Infinite, Homogeneous.",
"Brahman or the Absolute is free from difference of genus as between a tree and a rock, difference of species as between one tree and another, between leaf and flower of the same tree.",
"Atman is Absolute Consciousness, Brahman or the Bhuma (Infinite, unconditioned).",
"Existence is the same as consciousness.  Existence is really the existence of Consciousness.",
"Being (Satta, be-ness) is the Perfection of Existence.",
"There is no objectivity in Atmic consciousness, because Atman is second-less.",
"Consciousness is indivisible and homogeneous.",
"The Absolute is Self-luminosity, Non-duality, Self-consciousness, Independence.",
"Satyam Jnanam Anantam (Truth, Wisdom, Infinity); Satchidananda (Absolute Existence Knowledge Bliss); Prajnanam (Consciousness); Abhayam (fearlessness); Kham (bliss); Vijnanam,Anandam (Wisdom,Bliss); This is Brahman.",
"Absolute Consciousness is Pure Awareness.",
"Absolute Truth is one alone, there is no other.",
"Brahman is that, from which the origin, subsistence and dissolution of the world proceeded.",
"The Absolute Reality is not merely a matter of conception or metaphysical speculation. Brahman is free from the limitations of the attributer.  It is transcendental.",
"Brahman or the Absolute and the state of Nirvikalpa Samadhi cannot be defined or explained in words.  Language is imperfect and finite.",
"Brahman or the Absolute is without evolution and involution.",
"The Absolute knows Itself without any process of knowing.  He does not depend upon any cause or any instrument or any conjunction of circumstances for the revelation of His Existence.",
"The Absolute is above time and space, above all changes and relations, above all differences and limitations.  There is no substance either within or outside him.",
"He does not depend upon any cause or any instrument or any conjunction or circumstances for the revelation of His Existence.",
"Far more precious than many gold and diamond mines, is the spiritual wealth of Self-realization.",
"In Him alone you can find eternal bliss, everlasting peace, perennial joy, immortality and eternal life.",
"Therefore, seek Him, attain Him, through purity, selfless service, faith, devotion and wisdom.",
"Your sole duty is to realize God. Self-realization can be achieved in this very life, nay this very second.",
"God-realization is not a matter to be postponed till retirement. It is a vital urgent need to be attended to immediately.",
"The attainment of perfection is the goal of human life.",
"Realize Him.  You will have everything.  You will feel no want thereafter.",
"Self-realization is not for the cowards and weaklings, but for the brave, courageous and strong.",
"Be righteous.  Lead the life divine and attain God-realization in this very birth.",
"There is no shortcut to God-realization.",
"O Traveller in this earth plane! Start the pilgrimage right today.  Pray fervently.  Remember the Lord constantly.  You will surely reach the eternal abode.",
"O wanderer in the desert of this universe! O Pilgrim! O traveller! Beware of all mirages, of all temptations.  March directly to your goal - the mighty Oasis of Brahman.",
"O man! Thou art a pilgrim here.  Awake, awake.  Life is short.  Time is fleeting.  Go back to your original home of immortal bliss.",
"Divine knowledge can be found in the Upanishads, eternal fountain-source of the highest wisdom.",
"The Upanishad is the breath of the Eternal.  It is a revelation.  So it eternally inspires.",
"The Upanishads constitute the life-breath of India.  They are the direct revelations which are Eternal and Transcendental.",
"The Upanishads throw a flood of light on the path of knowledge and lead the aspirants to the highest rung on the ladder of Jnana (Wisdom).",
"Vedanta of the Upanishads is a living religion.  It is not mere dialectics.",
"Vedanta is a system of life itself.  It represents the fundamental basis on which alone a universal Religion, or \"a universal congress of faith\" can be built.",
"The Brihadaranyaka Upanishad is the oldest of the existing Upanishads.  It contains many treasures of spiritual knowledge.",
"Vedanta is the power that sustains India even today.",
"Vedanta is a non-dualistic philosophy.  It teaches that Brahman, ultimate Reality behind the phenomenal universe, is one without a second.",
"Hold aloft the Torch of Upanishadic wisdom and march forward to the Kingdom of Eternal Bliss and Immortality.  Upanishadic philosophy is the only solace of life.",
"Science analysis, classifies and explains phenomena, but Brahma-Vidya, or the science of the Self, teaches you to transcend phenomena and attain immortality.",
"The Upanishads are not the products of the individual mind and the intellect.  They are revelations.",
"The Upanishads contain the essence of the Vedic teaching.  The Upanishad is the pivot of Hindu culture.",
"The Upanishads are from the concluding portion of the Veda and are therefore called the Vedanta, or the end of the Vedas.",
"Know thou art the Infinite, unchanging, all-pervading Soul or Atman.",
"Atman is Pure-consciousness.  Self-knowledge and Self-delight.",
"In essence, you are pure Soul.  Desire, weakness, imperfection touch thee not.  Thou art not the body, nor the mind.",
"Appearance is in dwelt by Reality or Brahman.",
"The source for everything is God or Brahman or the Absolute.",
"The residue (after the practice of \"Neti-Neti\", after negation or sublation) is Brahman.",
"\’I\’, \’Mine\’, \’He\’, \’You\’, and \’Thine\’, \’This\’, \’That\’, \’Here\’, \’there\’, are all meaningless in the true sense.  The Absolute is the only Reality.  The Absolute alone exists.",
"Realize your unity with the Self.  That is the end and aim of life.",
"Brahman is the Reality, the delight of life,  the joy of mind, the fullness of peace, the Immortal.",
"Wake up! Wake up from the slumber of ignorance.  Realize the Self and be free.  This is the message of the Upanishads.",
"You need not try to become the Self or the Atman.  You are already the Self.  You should already know that.",
"Reject the superficial ego-personality, which claims \"I am Mr. Johnson, I am a doctor, I am tall,\" and know \"I am the all pervading Atman or Soul.\"",
"Real dictatorship will come when nationalism capitalism and militarism will perish, and humanism or humanitarianism, based on the Vedantic principle of the unity of the one life, takes their place.",
"Root yourself in Brahman. Develop equal vision.  You will shine as a Jivanmukta or liberated sage.",
"Become conscious of your immortal heritage - Atma Svarajya or Self-realisation.",
"Unite! Because the One Self is the great Unity in which all beings exist.",
"The Upanishads declare in unmistakable terms that man in essence is Brahman Himself.",
"Vedanta is not pantheism.  Vedanta recognizes only one non-dual Existence, Brahman.",
"There is no death!--This is the fundamental message which Vedanta proclaims.",
"The union with the Supreme Pure Consciousness forms the keynote of the Vedantic religion.",
"Vedanta teaches Sarvatma Bhava, the feeling of Self or Atman as All.",
"The religion of Vedanta is the realization of Brahman in the individual.",
"A Vedantin ignores the names and forms and beholds the one Atman in all.",
"Vedanta is a religion of the heart.  Vedanta teaches you the religion of oneness.  Vedanta is the final Reality.",
"Self-realization alone can give permanent satisfaction, eternal peace and immortal bliss.",
"Vedanta is no creed, no ceremony, or form of worship.  It is the supreme science of the Reality.",
"Vedanta boldly proclaims with emphasis that you are the immortal, all-pervading Atman in essence.",
"Only one Message have I for thee - Remember that thou art the all-pervading Immortal Atman or Soul.",
"Atman is the only Reality.  It is the Soul or the central core or the kernel of everything.",
"This Atman, this Supreme Self alone sees, but He is not seen.  He alone hears, but He is not heard.  He alone thinks, but He is not thought of.  Know Him and be free.",
"You are in essence the spiritual Being.  You are made up of the same substance of Satchidananda of which Brahman is made.",
"In the ether of the heart dwells the Ruler of all, the Lord of all, the King of all, the Governor of all, the Protector of all.  Realize Him and be happy.",
"This world is superimposed on Brahman or the Absolute.  That which is superimposed derives its existence from the substratum.  It does not exist apart from the substratum.",
"What is the highest achievement?  It is not wealth, position, power or titles or degrees.  What then?  It is Self-realization or Atma-Jnana (Knowledge of Self).",
"Individual soul is identical with the Supreme Soul. This is the central theme of the Upanishads.",
"In the state of absolute oneness,  there is not fate, no Karma, no obstacles, no impediment.",
"Whatever is, is in reality one.  There truly exists only one universal Being called Paramatman or the Supreme Absolute.",
"Where there is no duality, there is no fear, no disease, no death.",
"Where there is neither \’I\’ nor \’you\’, nor \’He\’, there is the Absolute or Brahman.",
"Feel that this Atman is untouched by miseries, pain and sufferings of the body and mind.  He is the silent witness, or Sakshi (Unattached Observer).",
"The Soul is Self-contained, All-full and Self-existent.",
"This Atman is the great Unity.  It is the highest freedom.",
"Atman is the fountain of all bliss.  Look within and be satisfied in you own Self.",
"The highest form of worship is the Knowledge: \"The individual soul and the Supreme Soul are identical\".",
"Hear all about Atman or Soul.  Then understand Atman.  Then reflect on Atman.  Then meditate on Atman.  Then realise Atman.  \’Tat Tvam Asi\’(\’That Thou Art\’).",
"You are, in essence, birth-less, deathless, diseaseless, changeless, decay-less,  Your real nature is blissful, eternal, all-pervading, infinite.",
"Lift veil after veil.  There shines the self-luminous Atman.  Thou art that self-radiance.",
"Attain the wisdom of the One.  Body-consciousness, fear, sorrow, doubt and delusion will vanish in toto.",
"Annihilate the sense of separateness.  Destroy the force of nescience or ignorance and become free and happy.",
"Atman is common Consciousness in all beings.  Atman of an ant, Atman of an elephant, Atman of a king, a peasant, rogue and a saint, is one and the same.",
"Death is only of the body, not of the Atman or the Supreme Soul.  The Supreme Soul is immortal.",
"The Atman neither dies, nor is born, nor has it any modification.",
"Moksha is in the heart of a man, which is free from hatred, lust, egoism, greed and desires.",
"Knowledge of Brahman destroys the root of all evils, such as nescience or ignorance, the seed of the entire Samsara.",
"Atman or the Self is dearer than the dearest of things.  It is nearer than the nearest.",
"Attain real spiritual strength through the Atman and Immortality, through wisdom of the Self.",
"Rise from the sense-life. Behold the one Atman in all beings and attain immortality and bliss eternal.",
"Renounce your ego and attain divinity.  Self-realization is here and now.",
"Man can become God or Brahman even while he is in body.",
"Perfection, freedom and independence are attained only by direct experience or wisdom of Atman.",
"Detach yourself from the unreal and attach yourself to the Real.  This is the way to attain Self-realization.",
"Thou art Atman!  Atman art Thou.  Realize this and be free. Nothing can hinder thee from the realization of thy essential nature.",
"All spiritual Sadhanas enjoined by the scriptures are only to remove the veil, the ego.",
"Know that wealth, sex-delights, power, learning are all bondage.  This is the beginning of wisdom.",
"Think and cogitate.  Realize the Self or Atman.  You will realize that life is a waking dream.",
"He Knows, who realizes the SELF(Big Self) within the self(small self).",
"Realize your oneness with the eternal and infinite Supreme Atman and thus go beyond all sufferings, sorrow, fear and death.",
"There is no bond equal in strength, to Maya.  There is no power greater than Yoga, to destroy this bond.",
"What a strange world!  How powerful is Maya!  In an instant she strangles the reason of man and pushes him down into the deep abyss of ignorance.",
"Ignorance is absence of wisdom of the Soul.  It is forgetfulness of one\’s essential divine nature.",
"All misery in the world is due to ignorance and false identification of the perishable body with the Imperishable Atman.",
"\’I\’, \’You\’, \’He\’, \’This\’, \’That\’ and the hosts of phantoms that Avidya creates, have always been illusory and delusive.",
"Banish all barriers from your mind.  Barriers are illusory products of Avidya or ignorance.",
"Ignorance is the progenitor of misery, disharmony and ruin.  Attain wisdom of the Self and be in harmony with all.",
"Ignorance is the root of the tree of egoism.  It is nourished by the currents of likes and dislikes.",
"Sacrifice is truly the sacrifice of egoism.",
"No vision of Truth, no vision of God, is possible without annihilating the ego.",
"Very difficult indeed, it is to sacrifice the ego. Ego persists.  Ego is deep-rooted.",
"This ego is a false non-entity.  It is a mere false shadow.  It is a false reflection.  It is a mirage.  It is a dream.",
"Empty yourself of your egoism; then the Divine will fill your heart to the brim.",
"You cannot realize the Infinite by mere metaphysical speculation.",
"Equip yourself with the four means.  Hear.  Reflect.  Meditate.  Then alone can you have integral experience or Self-realization.",
"God is a question of supply and demand.  So is Yogic aspiration.",
"Brahma Vidya should be imparted only to qualified students in Vedanta.  Then alone it becomes fruitful.",
"Love all, because all are the manifestations of the One Self.",
"The love you bear to anything is an aspect of the love that you bear to Brahman.  Things are dear, because the Self is mirrored in them.",
"The love that you bear to everything in this life is but a reflection of the love that you bear to the Atman.",
"The human love of the wife for her husband is a reflection of the Divine Love seated in her heart and responding to the Divine Love emanating from the husband.",
"With the wings of love and wisdom, fly to the immortal abode of Brahman.",
"Jnana Yoga is the subtle and analytical path of wisdom.",
"Wisdom will lead you to a realisation of the real oneness of Being.",
"Knowledge reveals itself.  It is not taught.  It embraces everything in its fold.",
"Knowledge of the ultimate cause means the knowledge of everything that exists.",
"Every moment of man is directed towards Satchidananda in a direct or indirect manner.",
"Eternal life is one, homogeneous and indivisible.",
"Wisdom is the Master-key to open the realms of eternal bliss and everlasting peace.",
"Practice self-denial.  Cultivate indifference or dispassion.  Practice meditation regularly.  This will enable you to enter the Kingdom of everlasting peace and bliss.",
"Peace dwells in Silence.  Silence is Brahman or the Absolute.",
"Seek internal peace of the Eternal, which will destroy all sorrows and pains and lead to final emancipation.",
"Righteousness forms the bed-rock of all religions.  Righteousness is the divine path. Bliss is for him who is righteous.",
"God is righteousness.  Righteousness is good. It is best.  Wealth, beauty, honour and youth fade away; but the life of righteousness and wisdom will never decay.",
"Keep up the love for life dedicated to righteousness.",
"Wisdom of the Self is the ripe fruit of the beautiful flower of virtue.",
"Do as you would be done by.  This is the gist of ethics.",
"Virtue conduces to happiness, vice to pain.",
"Supreme Goodness is God.  Lead the life of goodness.  To lead the life of goodness is to lead the life of all.",
"This body is meant for the good of others.  Righteousness is the support of the entire world.",
"There is Truth where righteousness is.  Realize the Truth by practicing righteousness.",
"Righteousness is the best acquisition of man.  It is the world\’s highest wealth.",
"To live in perfect goodness is to dissolve in the Infinite.",
"Purity is the first requisite for God-realization.  Therefore cultivate purity.",
"In purity is the secret of God-realization, in self-restraint, the strength of character; and in dispassion spiritual progress.",
"Purity is the pathway to the Kingdom of God.  Therefore, be pure in your thought, word and deed.",
"Study of sacred scriptures without purity of mind, reflection and meditation is only waste of time.",
"The mere reading of Vedantic texts, the Upanishads and Brahma Sutras without purity of heart will neither bring true understanding, nor fruitful results.",
"A pure heart is necessary to know the Will of God.",
"If you wish to be strong, be pure.  Mere bodily purity without the purity of the heart is absolutely useless.",
"Mental purity is of paramount importance for Self-realization.",
"Purity is freedom from desire. Purity is the passport to the foreign land of Eternal Bliss.",
"Purity is the best jewel of a Yogi.  It is the greatest treasure of a sage.  It is the best wealth of a devotee.",
"Only the pure in heart can attain God-realization.",
"Stick to Ahimsa (Non-Violence), Satyam (Truth) and Brahmacharya (Celibacy), if you want to evolve quickly in spirituality.",
"If you are established in Ahimsa (Non-Violence), you have attained all virtues.",
"You cannot Practice Ahimsa(Non-Violence) without practicing truth.",
"Ahimsa (Non-Violence) is the pivot.  All virtues revolve round Ahimsa.",
"Ahimsa is not mere negative non-injuring. It is positive, cosmic love.",
"Ahimsa is cosmic love.  Ahimsa is true sacrifice.  Ahimsa is forgiveness.  Ahimsa is true strength.",
"Truth is the Gateway to the Kingdom of God.",
"There is no virtue like Truthfulness.",
"Truth stands even when there is no public support.",
"Think truly.  Speak truly.  Live truly.  Act truly.",
"Thought must agree with your word and word with your deed.  This will transform you into divinity.",
"Attain Truth through speaking the truth and practicing truth in all your daily actions and behaviour towards others.",
"Study the lives of saints and draw inspiration from them who led a life of truth.",
"The basis of body-building and spiritual growth is Brahmacharya",
"Brahmacharya is an integral part of Yoga.  It is an indispensable factor for divine union or blissful Samadhi.",
"Sex-urge is a creative force.  Direct the sex-energy to the higher spiritual channel.  It will be sublimated.  It will be transformed into divine energy.",
"Unless you are inspired by spiritual ideals, it is difficult to keep the sexual instinct in check.",
"Overcome lust by the practice of Brahmacharya.",
"Character is the term which designates the distinctive qualities a person manifests in his relationship with his fellows.",
"There are all shades and degrees of character from the highest to the lowest.",
"Pure, noble and good character or Sadachara forms an indispensable part of spiritual life.",
"Your life will become much poorer in quality, if the spiritual element and moral standards are lacking.",
"Character is like catching a contagious disease.  Acquire it by Satsanga or the company of good people. This is the best way.",
"Discipline breeds character, character perfects the individual, individual builds nation.",
"The secret of beauty is not dress and ornaments, but good character and the possession of divine virtues.",
"Character is what you are, reputation is what people think you are.  The best treasure of a man is noble character.",
"Get rid of the personal element in you to begin with.  When anyone injures you train yourself to cease to resent it.  Try.  Try.  Try.",
"If you do not know the laws of right conduct, you cannot form your character.",
"Morality is the gateway to religion.  Morality is the gateway to bliss immortal.",
"Sense-control leads to peace and happiness.",
"Where there is kindness, humility and purity, spirituality springs up, saintliness shines, divinity descends and perfection manifests itself.",
"Man needs now no more degrees, but character, no more study but wisdom.",
"He lives in the hearts of all, who is true to his own heart, who is pure, virtuous and who serves all selflessly.",
"He who has a blameless character and good behaviour can realize the Truth quickly.",
"Forgiveness is the greatest virtue, which shines forth in all its splendour in the devotee.",
"Courage and patience are the twin qualities of a real aspirant.",
"Humility is the highest of all virtues.  God helps you, only when you feel utterly humble.",
"Humility is not cowardice.  Meekness is not weakness.  Humility and meekness are indeed spiritual powers.",
"Make patience thy strength.  Non-attachment comes very slowly.  It gives a new sense of freedom and peace.",
"Strongly assert, feel and will \"I am courage itself.  I am an embodiment of courage.\" Fear will disappear.",
"Anger is the worst fire.  Lust is an all-consuming fire.",
"Anger and lust scorch your heart.  Extinguish these fires through love and purity.",
"Meditate \"I am fearless, Immortal Soul.\" Fear will vanish.",
"True love is the greatest power on this earth.  It rules without a sword and binds without a cord.",
"Make love thy armour. To love God is to love all.  To love all is to love God.",
"Make love your treasure.  Spread the message of love.",
"All are manifestations of the Lord.  Love all equally.  Again and again strive.",
"Practice cosmic love.  Love all.  Embrace all.  Be kind to all.  This will remove jealousy, hatred, etc.",
"Love all.  This is the secret of Self-realization and liberation.",
"Adaptability, kind speech, pure conduct, patience--are the four fundamental virtues.",
"Justice, temperance, courage, wisdom and holiness are the five great virtues.",
"Virtue is the most precious treasure.  Acquire this treasure in abundance.",
"Virtue is the golden key which opens the gate of the abode of Bliss Eternal.",
"The three great virtues are courage, benevolence and purity.",
"Cultivate the divine virtues such as purity, courage, humility, self-restraint, non-violence, truth, mercy, faith.",
"Be virtuous.  You are on the way to Wisdom.",
"In the garden of your heart plant the lily of love, the rose of purity, the Champaka of courage, the Mandara of humility and the lady-of-the-night of compassion.",
"Be in the world, but not of the world.  Lead a simple life.  Lead a regulated life.",
"Enthrone the Lord in thy heart.  Be a hero in the internal fight.  Have the goal in sight.  Disseminate what is right.",
"Teach your children to feel they are the future citizens of the world.",
"Ever live within your income.  Save when you are young.  Spend when you are old.  Never run into debt.",
"God is the Inner Ruler.  Root yourself in God.",
"Immortality is thy birthright.  Realize this now and here.",
"Expand.  Evolve.  Grow.  Forget not the goal.  Awake.  Achieve the goal.",
"Control the mind.  Have a balanced mind.  Coax the mind.  Discipline the mind.  Keep the mind fully occupied.",
"Enquire who am I?  Search, understand, and realize. There is only one Atman.  Feel oneness with all.",
"Be tolerant.  Behold the unity of all faiths, cults, creeds and religions.  Respect the views, opinions and sentiments of all.",
"There is some truth in everything.  Views and opinions are different aspects.  Do not quarrel with others.",
"Behold the Light that lightens everywhere.  Strive for the divine life.  You will attain eternal peace and immortality.",
"Concentrate all your attention on the work at hand.  Live this day well.  Yesterday has joined the hoary past, a finished product, on which you need bestow no more attention.  Tomorrow is yet a long way off; and it will bring with it time enough for its work.  Forget the past; ignore the future.  Live in the present.  The future will take care of itself.",
"Sparks of the divine flame!  Tread the path of righteousness and truth, which is the way of love, which is the way of Light.",
"Walk in the foot-steps of the great Saviours and Saints of the world.",
"Associate with the Saints and Sages, and grow in purity and wisdom.",
"Thirst for the vision of God.  Have real spiritual hunger.",
"Admit your faults and weaknesses.  Then alone will you evolve.",
"Eradicate self-justification.  Then alone can you annihilate your ego.",
"Stick to your principles.  Be adamant.  Spiritual Sadhana alone can transform you into divinity.",
"Draw strength and power from within.  Atman is a magazine of infinite power and strength.",
"Ignorance, desire and selfish works are the fetters that bind you.  Break them and be free.",
"Train yourself in the language of God.  Silence is His language.  Introspect, and search Him inside your heart.",
"Meditation and contentment are the secrets of good health and longevity.",
"Look within.  Gaze within. Remove the veil.  Attain knowledge of Self.  Knowledge gives freedom. Knowledge slays ignorance or Avidya.",
"Meditate in Brahmamuhurta.  Practice meditation regularly.  Meditation leads to eternal bliss.  Therefore meditate, meditate.",
"Tap the source and attain strength, power and wisdom.",
"Be humble.  Be simple.  Be gentle.  Be sweet.  Be frank like a child.  You will enter the realm of eternal bliss.",
"Gird up your loins.  Be up and doing.  You will attain success in everything.",
"Withdraw the senses.  Meditate.  Be in tune with the Infinite.  Meditate.  Taste the eternal bliss.  Realize the Infinite Bliss.",
"Become silent.  In Silence the truth will shine.  Look within.  Be still.   Hear the Inner Voice of God.",
"Feel you are all-pervading Atman.  Live in Atman.  Rejoice in Atman.",
"Develop pure love.  Have a broad vision.  Love all. Serve all. Behold the Self in all.",
"Appearance is in-dwelt by Reality or Brahman.",
"You cannot know the love of God, till you remove your sense of \’I\’-ness, and \’mine\’-ness.",
"When you love God, you love everything.  All are His manifestations.",
"When you love God, the entire world becomes dear to you.  The highest use of life is to live it in the service of all beings.",
"Love knows no reward.  Love knows no fear.",
"Space is no limitation.  Distance is no barrier.  Thou art the all-pervading Soul.",
"Saturate your mind with divine thoughts.",
"God is immanent in the universe.",
"There is no pleasure in finite things.  The Infinite alone is bliss itself.",
"Live in tune with the Infinite.  Rejoice in the Self within.  This is the great slogan of life.",
"Life is very precious.  Time is very precious.",
"This world is your body.  This world is a great school. This world is your silent teacher.",
"Live in the present, forget the past.  Give up hopes of future.",
"Think rightly. Act rightly.  Learn to discriminate.",
"Acquire spiritual wealth.  Spiritual wealth is most precious and inexhaustible.",
"If you attain the knowledge of Brahman, everything becomes known to you.",
"Know that Prakriti or Pradhan is an illusion.  You create your own world of worries and troubles.  No one forces it on you.",
"Feel that you are serving the Lord and Lord alone in the members of you family.",
"The flesh wars ceaselessly against the Spirit.  Therefore be ever vigilant.",
"Blend your love for your wife, son and property into one and direct it to God.  You will attain God-realization this very second.",
"How hollow is life mundane!  Trust not the senses.  Go thou beyond!  Reach the realm of Bliss Immortal.",
"Love is the fulfilment of the Law. Understand the Law, and attain power and wisdom.",
"The essential condition of spirituality is the annihilation of desire for mundane objects.  You should have Vairagya or dispassion.",
"It is hard to attain Peace.  Sincere, intense longing is essential.",
"Prepare the soil of your heart.  The Guru will appear before you and sow the spiritual seed.",
"Brutal nature in you is an enemy of divine life.  Burn this lower nature to ashes.",
"Bear all trials, face all dangers, be brave and fearless.  You are now fit to attain Immortality.",
"Take hold of each day, as if it were the last day, and utilize every second in prayers, meditation and service.",
"Be prepared.  Live as though you are even now about to die.",
"The means of escaping from this endless Samsara are self-restraint, purity, devotion, aspiration, reflection and meditation.",
"The only thing worth seeking after in life is God.  God alone exists.  All else is vanity.",
"Find bliss, strength, peace, power and light and wisdom in renunciation.",
"The first test of a truly great man is his humility, simplicity, love and mercy.",
"If anyone injures you, forgive him and forget the injury done by him.  You will gain immense spiritual strength.",
"Sensual pleasure is a mirage.  It has no reality.  It is always subject to reaction and pain.",
"Pure love is sublime.  It is divine.  It fears nothing.  It knows no limit. It is everywhere.",
"Ignorance is the cause of bondage.  It is removed by Knowledge.",
"Be catholic and liberal in your views.  Expand. Evolve.  Grow.  Unite with all.  Ignore trifles.",
"God is in the roar of a lion, the song of a bird, and the cry of a babe.  Feel His Presence everywhere.",
"Sacrifice and service are your two hands.  Freedom and peace are your two legs.  Love and bliss are your two eyes.  Truth and devotion are your two ears.  Self-knowledge is your mouth.  Perfection is, indeed, your heart and soul.",
"Without service and love, heart will remain barren.",
"Selfishness is the thorn of life.  What God wants first and foremost, is the purity of heart.",
"O Man!  Hearken to the words of saints and sages, and attain wisdom.  Waste not this precious life.",
"Write the words \"Serve, love, give, purify, meditate, realize, be good, do good, be kind, be compassionate. Enquire who am I? Know the Self, and be free.  \"Adapt, adjust, accommodate\" on the tablet of your heart.  You will hear the music of the Soul and be drowned in the ocean of Bliss and Peace.",
"Live not to satisfy the palate and the sense, but live to realize the Self within.",
"Be righteous.  Develop virtuous qualities.  Establish good habits.  Eradicate all evil habits.",
"Speak measured words, and control lingual diarrhoea. Develop the power of endurance.  Lead a hard life.",
"To behold the one Atman or Soul in a dog, elephant, cow, ant, outcaste, roque and in all forms is Jnana or Wisdom.",
"Terrible is the attachment to the body.  Remove the attachment through dispassion, discrimination and inquiry.",
"You can be a very good scholar, but still be far from religion or the pious life.",
"You should seek a renewal of the spiritual life, as a solution to many of the problems that confront you today.",
"Moral values, culture and religion, maintaining these values is far better than laws and regulations.",
"We require truly religious men in public services.",
"Have a simple and unassuming manner of life.  Live not to eat, but eat to live.",
"A good word for a bad one is worth much but costs little.",
"Bear no envy.  Commit no slander.  Speak no falsehood.  Practice no deceit.  Harbour no malice.  You will be ever joyful, happy and peaceful.",
"Forget the mistakes of the past.  Be righteous and correct yourself from now.",
"Kindness does not consist in gifts, but in gentleness and generosity.",
"The sweetness of life is devotion.  The fragrance of life is generosity. The pivot of life is meditation.  The goal of life is Self-realization.  Therefore, Serve, Love, Be Pure and generous.  Meditate and realize.",
"O Ram!  You cannot avoid the Law of Karma.  It is only the Self-knowledge that can burn all Karmas.  Your Karma will bring you happiness and misery, both, according to your previous deeds.  Feel: \"Even this will pass away.\"  Balance the mind in pleasure and pain.  Rest in the ever blissful Atman, which is beyond the reach of Karma.  Destroy Karma through the fire of Atma Jnana (Knowledge of the Self).",
"The sole object of life is the attainment of Self-realization or Absolute Freedom.  Devote every minute of your life for this grand attainment."
];
  
  